version: '3.8'
services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    depends_on:
      - mongo-primary
      - mongo-secondary-1
      - mongo-secondary-2
    networks:
      - mongo-network

  mongo-primary:
    image: mongo:7.0
    container_name: mongo-primary
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: 'rs0'
    volumes:
      - mongo-primary-data:/data/db
      - ${PWD}/rs_keyfile:/opt/mongo-keyfile
    command:
      [
        'mongod',
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--keyFile',
        '/opt/mongo-keyfile',
      ]
    networks:
      - mongo-network

  mongo-secondary-1:
    image: mongo:7.0
    container_name: mongo-secondary-1
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: 'rs0'
    volumes:
      - mongo-secondary-1-data:/data/db
      - ${PWD}/rs_keyfile:/opt/mongo-keyfile
    command:
      [
        'mongod',
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--keyFile',
        '/opt/mongo-keyfile',
      ]
    networks:
      - mongo-network

  mongo-secondary-2:
    image: mongo:7.0
    container_name: mongo-secondary-2
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: 'rs0'
    volumes:
      - mongo-secondary-2-data:/data/db
      - ${PWD}/rs_keyfile:/opt/mongo-keyfile
    command:
      [
        'mongod',
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--keyFile',
        '/opt/mongo-keyfile',
      ]
    networks:
      - mongo-network

volumes:
  mongo-primary-data:
  mongo-secondary-1-data:
  mongo-secondary-2-data:

networks:
  mongo-network:
    driver: bridge
